version: '3.3'
services:
  postgres_db:
    image: postgres:12
    command: postgres -c 'max_connections=1000'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints:
          - node.labels.postgres == true
    environment:
      POSTGRES_DB: covid_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql
    networks:
      - covid-network

  web-client:
    build: .
    ports:
      - "8082:8082"
    environment:
      POSTGRESQL_DATABASE: covid_service
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_HOST: postgres_db
    networks:
      - covid-network
    depends_on:
      - postgres_db

volumes:
  covid-postgres-data:

networks:
  covid-network:
