INSERT INTO countries (code, name, slug) VALUES ('EE', 'Estonia', 'estonia');
INSERT INTO countries (code, name, slug) VALUES ('CO', 'Colombia', 'colombia');
INSERT INTO countries (code, name, slug) VALUES ('CD', 'Congo (Kinshasa)', 'congo-kinshasa');
INSERT INTO countries (code, name, slug) VALUES ('BD', 'Bangladesh', 'bangladesh');
INSERT INTO countries (code, name, slug) VALUES ('PF', 'French Polynesia', 'french-polynesia');
INSERT INTO countries (code, name, slug) VALUES ('SG', 'Singapore', 'singapore');
INSERT INTO countries (code, name, slug) VALUES ('ZA', 'South Africa', 'south-africa');
INSERT INTO countries (code, name, slug) VALUES ('TV', 'Tuvalu', 'tuvalu');
INSERT INTO countries (code, name, slug) VALUES ('BV', 'Bouvet Island', 'bouvet-island');
INSERT INTO countries (code, name, slug) VALUES ('DE', 'Germany', 'germany');
INSERT INTO countries (code, name, slug) VALUES ('HM', 'Heard and Mcdonald Islands', 'heard-and-mcdonald-islands');
INSERT INTO countries (code, name, slug) VALUES ('KZ', 'Kazakhstan', 'kazakhstan');
INSERT INTO countries (code, name, slug) VALUES ('AI', 'Anguilla', 'anguilla');
INSERT INTO countries (code, name, slug) VALUES ('CZ', 'Czech Republic', 'czech-republic');
INSERT INTO countries (code, name, slug) VALUES ('SJ', 'Svalbard and Jan Mayen Islands', 'svalbard-and-jan-mayen-islands');
INSERT INTO countries (code, name, slug) VALUES ('ES', 'Spain', 'spain');
INSERT INTO countries (code, name, slug) VALUES ('MQ', 'Martinique', 'martinique');
INSERT INTO countries (code, name, slug) VALUES ('SO', 'Somalia', 'somalia');
INSERT INTO countries (code, name, slug) VALUES ('US', 'United States of America', 'united-states');
INSERT INTO countries (code, name, slug) VALUES ('BO', 'Bolivia', 'bolivia');
INSERT INTO countries (code, name, slug) VALUES ('HR', 'Croatia', 'croatia');
INSERT INTO countries (code, name, slug) VALUES ('RW', 'Rwanda', 'rwanda');
INSERT INTO countries (code, name, slug) VALUES ('MF', 'Saint-Martin (French part)', 'saint-martin-french-part');
INSERT INTO countries (code, name, slug) VALUES ('CK', 'Cook Islands', 'cook-islands');
INSERT INTO countries (code, name, slug) VALUES ('BT', 'Bhutan', 'bhutan');
INSERT INTO countries (code, name, slug) VALUES ('CN', 'China', 'china');
INSERT INTO countries (code, name, slug) VALUES ('ET', 'Ethiopia', 'ethiopia');
INSERT INTO countries (code, name, slug) VALUES ('FO', 'Faroe Islands', 'faroe-islands');
INSERT INTO countries (code, name, slug) VALUES ('IS', 'Iceland', 'iceland');
INSERT INTO countries (code, name, slug) VALUES ('SV', 'El Salvador', 'el-salvador');
INSERT INTO countries (code, name, slug) VALUES ('HT', 'Haiti', 'haiti');
INSERT INTO countries (code, name, slug) VALUES ('NL', 'Netherlands', 'netherlands');
INSERT INTO countries (code, name, slug) VALUES ('SY', 'Syrian Arab Republic (Syria)', 'syria');
INSERT INTO countries (code, name, slug) VALUES ('TZ', 'Tanzania, United Republic of', 'tanzania');
INSERT INTO countries (code, name, slug) VALUES ('CF', 'Central African Republic', 'central-african-republic');
INSERT INTO countries (code, name, slug) VALUES ('AF', 'Afghanistan', 'afghanistan');
INSERT INTO countries (code, name, slug) VALUES ('NC', 'New Caledonia', 'new-caledonia');
INSERT INTO countries (code, name, slug) VALUES ('VU', 'Vanuatu', 'vanuatu');
INSERT INTO countries (code, name, slug) VALUES ('FM', 'Micronesia, Federated States of', 'micronesia');
INSERT INTO countries (code, name, slug) VALUES ('NZ', 'New Zealand', 'new-zealand');
INSERT INTO countries (code, name, slug) VALUES ('TJ', 'Tajikistan', 'tajikistan');
INSERT INTO countries (code, name, slug) VALUES ('TO', 'Tonga', 'tonga');
INSERT INTO countries (code, name, slug) VALUES ('TM', 'Turkmenistan', 'turkmenistan');
INSERT INTO countries (code, name, slug) VALUES ('MG', 'Madagascar', 'madagascar');
INSERT INTO countries (code, name, slug) VALUES ('DJ', 'Djibouti', 'djibouti');
INSERT INTO countries (code, name, slug) VALUES ('IL', 'Israel', 'israel');
INSERT INTO countries (code, name, slug) VALUES ('LA', 'Lao PDR', 'lao-pdr');
INSERT INTO countries (code, name, slug) VALUES ('RU', 'Russian Federation', 'russia');
INSERT INTO countries (code, name, slug) VALUES ('AL', 'Albania', 'albania');
INSERT INTO countries (code, name, slug) VALUES ('BS', 'Bahamas', 'bahamas');
INSERT INTO countries (code, name, slug) VALUES ('CR', 'Costa Rica', 'costa-rica');
INSERT INTO countries (code, name, slug) VALUES ('GL', 'Greenland', 'greenland');
INSERT INTO countries (code, name, slug) VALUES ('VA', 'Holy See (Vatican City State)', 'holy-see-vatican-city-state');
INSERT INTO countries (code, name, slug) VALUES ('SD', 'Sudan', 'sudan');
INSERT INTO countries (code, name, slug) VALUES ('CC', 'Cocos (Keeling) Islands', 'cocos-keeling-islands');
INSERT INTO countries (code, name, slug) VALUES ('AN', 'Netherlands Antilles', 'netherlands-antilles');
INSERT INTO countries (code, name, slug) VALUES ('OM', 'Oman', 'oman');
INSERT INTO countries (code, name, slug) VALUES ('RO', 'Romania', 'romania');
INSERT INTO countries (code, name, slug) VALUES ('AE', 'United Arab Emirates', 'united-arab-emirates');
INSERT INTO countries (code, name, slug) VALUES ('VN', 'Viet Nam', 'vietnam');
INSERT INTO countries (code, name, slug) VALUES ('EH', 'Western Sahara', 'western-sahara');
INSERT INTO countries (code, name, slug) VALUES ('AT', 'Austria', 'austria');
INSERT INTO countries (code, name, slug) VALUES ('CV', 'Cape Verde', 'cape-verde');
INSERT INTO countries (code, name, slug) VALUES ('TC', 'Turks and Caicos Islands', 'turks-and-caicos-islands');
INSERT INTO countries (code, name, slug) VALUES ('GY', 'Guyana', 'guyana');
INSERT INTO countries (code, name, slug) VALUES ('RE', 'Réunion', 'réunion');
INSERT INTO countries (code, name, slug) VALUES ('GS', 'South Georgia and the South Sandwich Islands', 'south-georgia-and-the-south-sandwich-islands');
INSERT INTO countries (code, name, slug) VALUES ('PH', 'Philippines', 'philippines');
INSERT INTO countries (code, name, slug) VALUES ('NR', 'Nauru', 'nauru');
INSERT INTO countries (code, name, slug) VALUES ('NU', 'Niue', 'niue');
INSERT INTO countries (code, name, slug) VALUES ('SM', 'San Marino', 'san-marino');
INSERT INTO countries (code, name, slug) VALUES ('HK', 'Hong Kong, SAR China', 'hong-kong-sar-china');
INSERT INTO countries (code, name, slug) VALUES ('IT', 'Italy', 'italy');
INSERT INTO countries (code, name, slug) VALUES ('MR', 'Mauritania', 'mauritania');
INSERT INTO countries (code, name, slug) VALUES ('PN', 'Pitcairn', 'pitcairn');
INSERT INTO countries (code, name, slug) VALUES ('RS', 'Serbia', 'serbia');
INSERT INTO countries (code, name, slug) VALUES ('JO', 'Jordan', 'jordan');
INSERT INTO countries (code, name, slug) VALUES ('GQ', 'Equatorial Guinea', 'equatorial-guinea');
INSERT INTO countries (code, name, slug) VALUES ('IN', 'India', 'india');
INSERT INTO countries (code, name, slug) VALUES ('MA', 'Morocco', 'morocco');
INSERT INTO countries (code, name, slug) VALUES ('PG', 'Papua New Guinea', 'papua-new-guinea');
INSERT INTO countries (code, name, slug) VALUES ('BR', 'Brazil', 'brazil');
INSERT INTO countries (code, name, slug) VALUES ('BN', 'Brunei Darussalam', 'brunei');
INSERT INTO countries (code, name, slug) VALUES ('SH', 'Saint Helena', 'saint-helena');
INSERT INTO countries (code, name, slug) VALUES ('EG', 'Egypt', 'egypt');
INSERT INTO countries (code, name, slug) VALUES ('PY', 'Paraguay', 'paraguay');
INSERT INTO countries (code, name, slug) VALUES ('JE', 'Jersey', 'jersey');
INSERT INTO countries (code, name, slug) VALUES ('UA', 'Ukraine', 'ukraine');
INSERT INTO countries (code, name, slug) VALUES ('KH', 'Cambodia', 'cambodia');
INSERT INTO countries (code, name, slug) VALUES ('TD', 'Chad', 'chad');
INSERT INTO countries (code, name, slug) VALUES ('TL', 'Timor-Leste', 'timor-leste');
INSERT INTO countries (code, name, slug) VALUES ('IM', 'Isle of Man', 'isle-of-man');
INSERT INTO countries (code, name, slug) VALUES ('GH', 'Ghana', 'ghana');
INSERT INTO countries (code, name, slug) VALUES ('VI', 'Virgin Islands, US', 'virgin-islands');
INSERT INTO countries (code, name, slug) VALUES ('GA', 'Gabon', 'gabon');
INSERT INTO countries (code, name, slug) VALUES ('TT', 'Trinidad and Tobago', 'trinidad-and-tobago');
INSERT INTO countries (code, name, slug) VALUES ('BE', 'Belgium', 'belgium');
INSERT INTO countries (code, name, slug) VALUES ('DK', 'Denmark', 'denmark');
INSERT INTO countries (code, name, slug) VALUES ('PE', 'Peru', 'peru');
INSERT INTO countries (code, name, slug) VALUES ('BB', 'Barbados', 'barbados');
INSERT INTO countries (code, name, slug) VALUES ('FK', 'Falkland Islands (Malvinas)', 'falkland-islands-malvinas');
INSERT INTO countries (code, name, slug) VALUES ('AS', 'American Samoa', 'american-samoa');
INSERT INTO countries (code, name, slug) VALUES ('GF', 'French Guiana', 'french-guiana');
INSERT INTO countries (code, name, slug) VALUES ('GI', 'Gibraltar', 'gibraltar');
INSERT INTO countries (code, name, slug) VALUES ('KW', 'Kuwait', 'kuwait');
INSERT INTO countries (code, name, slug) VALUES ('LV', 'Latvia', 'latvia');
INSERT INTO countries (code, name, slug) VALUES ('PT', 'Portugal', 'portugal');
INSERT INTO countries (code, name, slug) VALUES ('SA', 'Saudi Arabia', 'saudi-arabia');
INSERT INTO countries (code, name, slug) VALUES ('KI', 'Kiribati', 'kiribati');
INSERT INTO countries (code, name, slug) VALUES ('MY', 'Malaysia', 'malaysia');
INSERT INTO countries (code, name, slug) VALUES ('GG', 'Guernsey', 'guernsey');
INSERT INTO countries (code, name, slug) VALUES ('ID', 'Indonesia', 'indonesia');
INSERT INTO countries (code, name, slug) VALUES ('BA', 'Bosnia and Herzegovina', 'bosnia-and-herzegovina');
INSERT INTO countries (code, name, slug) VALUES ('FJ', 'Fiji', 'fiji');
INSERT INTO countries (code, name, slug) VALUES ('KE', 'Kenya', 'kenya');
INSERT INTO countries (code, name, slug) VALUES ('KP', 'Korea (North)', 'korea-north');
INSERT INTO countries (code, name, slug) VALUES ('ST', 'Sao Tome and Principe', 'sao-tome-and-principe');
INSERT INTO countries (code, name, slug) VALUES ('UY', 'Uruguay', 'uruguay');
INSERT INTO countries (code, name, slug) VALUES ('CY', 'Cyprus', 'cyprus');
INSERT INTO countries (code, name, slug) VALUES ('EC', 'Ecuador', 'ecuador');
INSERT INTO countries (code, name, slug) VALUES ('GE', 'Georgia', 'georgia');
INSERT INTO countries (code, name, slug) VALUES ('MH', 'Marshall Islands', 'marshall-islands');
INSERT INTO countries (code, name, slug) VALUES ('MM', 'Myanmar', 'myanmar');
INSERT INTO countries (code, name, slug) VALUES ('PL', 'Poland', 'poland');
INSERT INTO countries (code, name, slug) VALUES ('AW', 'Aruba', 'aruba');
INSERT INTO countries (code, name, slug) VALUES ('BZ', 'Belize', 'belize');
INSERT INTO countries (code, name, slug) VALUES ('SE', 'Sweden', 'sweden');
INSERT INTO countries (code, name, slug) VALUES ('MW', 'Malawi', 'malawi');
INSERT INTO countries (code, name, slug) VALUES ('MP', 'Northern Mariana Islands', 'northern-mariana-islands');
INSERT INTO countries (code, name, slug) VALUES ('LI', 'Liechtenstein', 'liechtenstein');
INSERT INTO countries (code, name, slug) VALUES ('NG', 'Nigeria', 'nigeria');
INSERT INTO countries (code, name, slug) VALUES ('UZ', 'Uzbekistan', 'uzbekistan');
INSERT INTO countries (code, name, slug) VALUES ('AQ', 'Antarctica', 'antarctica');
INSERT INTO countries (code, name, slug) VALUES ('CI', 'Côte d''Ivoire', 'cote-divoire');
INSERT INTO countries (code, name, slug) VALUES ('IQ', 'Iraq', 'iraq');
INSERT INTO countries (code, name, slug) VALUES ('GM', 'Gambia', 'gambia');
INSERT INTO countries (code, name, slug) VALUES ('BF', 'Burkina Faso', 'burkina-faso');
INSERT INTO countries (code, name, slug) VALUES ('ER', 'Eritrea', 'eritrea');
INSERT INTO countries (code, name, slug) VALUES ('GT', 'Guatemala', 'guatemala');
INSERT INTO countries (code, name, slug) VALUES ('PR', 'Puerto Rico', 'puerto-rico');
INSERT INTO countries (code, name, slug) VALUES ('PM', 'Saint Pierre and Miquelon', 'saint-pierre-and-miquelon');
INSERT INTO countries (code, name, slug) VALUES ('TR', 'Turkey', 'turkey');
INSERT INTO countries (code, name, slug) VALUES ('DZ', 'Algeria', 'algeria');
INSERT INTO countries (code, name, slug) VALUES ('ME', 'Montenegro', 'montenegro');
INSERT INTO countries (code, name, slug) VALUES ('NE', 'Niger', 'niger');
INSERT INTO countries (code, name, slug) VALUES ('BL', 'Saint-Barthélemy', 'saint-barthélemy');
INSERT INTO countries (code, name, slug) VALUES ('WF', 'Wallis and Futuna Islands', 'wallis-and-futuna-islands');
INSERT INTO countries (code, name, slug) VALUES ('BY', 'Belarus', 'belarus');
INSERT INTO countries (code, name, slug) VALUES ('JM', 'Jamaica', 'jamaica');
INSERT INTO countries (code, name, slug) VALUES ('MX', 'Mexico', 'mexico');
INSERT INTO countries (code, name, slug) VALUES ('MC', 'Monaco', 'monaco');
INSERT INTO countries (code, name, slug) VALUES ('NP', 'Nepal', 'nepal');
INSERT INTO countries (code, name, slug) VALUES ('GW', 'Guinea-Bissau', 'guinea-bissau');
INSERT INTO countries (code, name, slug) VALUES ('BH', 'Bahrain', 'bahrain');
INSERT INTO countries (code, name, slug) VALUES ('AO', 'Angola', 'angola');
INSERT INTO countries (code, name, slug) VALUES ('IE', 'Ireland', 'ireland');
INSERT INTO countries (code, name, slug) VALUES ('LY', 'Libya', 'libya');
INSERT INTO countries (code, name, slug) VALUES ('LT', 'Lithuania', 'lithuania');
INSERT INTO countries (code, name, slug) VALUES ('MU', 'Mauritius', 'mauritius');
INSERT INTO countries (code, name, slug) VALUES ('MD', 'Moldova', 'moldova');
INSERT INTO countries (code, name, slug) VALUES ('WS', 'Samoa', 'samoa');
INSERT INTO countries (code, name, slug) VALUES ('SK', 'Slovakia', 'slovakia');
INSERT INTO countries (code, name, slug) VALUES ('CH', 'Switzerland', 'switzerland');
INSERT INTO countries (code, name, slug) VALUES ('TF', 'French Southern Territories', 'french-southern-territories');
INSERT INTO countries (code, name, slug) VALUES ('LU', 'Luxembourg', 'luxembourg');
INSERT INTO countries (code, name, slug) VALUES ('ZW', 'Zimbabwe', 'zimbabwe');
INSERT INTO countries (code, name, slug) VALUES ('AG', 'Antigua and Barbuda', 'antigua-and-barbuda');
INSERT INTO countries (code, name, slug) VALUES ('CM', 'Cameroon', 'cameroon');
INSERT INTO countries (code, name, slug) VALUES ('LR', 'Liberia', 'liberia');
INSERT INTO countries (code, name, slug) VALUES ('VG', 'British Virgin Islands', 'british-virgin-islands');
INSERT INTO countries (code, name, slug) VALUES ('VC', 'Saint Vincent and Grenadines', 'saint-vincent-and-the-grenadines');
INSERT INTO countries (code, name, slug) VALUES ('GN', 'Guinea', 'guinea');
INSERT INTO countries (code, name, slug) VALUES ('SC', 'Seychelles', 'seychelles');
INSERT INTO countries (code, name, slug) VALUES ('GB', 'United Kingdom', 'united-kingdom');
INSERT INTO countries (code, name, slug) VALUES ('VE', 'Venezuela (Bolivarian Republic)', 'venezuela');
INSERT INTO countries (code, name, slug) VALUES ('AU', 'Australia', 'australia');
INSERT INTO countries (code, name, slug) VALUES ('LB', 'Lebanon', 'lebanon');
INSERT INTO countries (code, name, slug) VALUES ('KG', 'Kyrgyzstan', 'kyrgyzstan');
INSERT INTO countries (code, name, slug) VALUES ('PW', 'Palau', 'palau');
INSERT INTO countries (code, name, slug) VALUES ('YE', 'Yemen', 'yemen');
INSERT INTO countries (code, name, slug) VALUES ('BM', 'Bermuda', 'bermuda');
INSERT INTO countries (code, name, slug) VALUES ('BW', 'Botswana', 'botswana');
INSERT INTO countries (code, name, slug) VALUES ('CX', 'Christmas Island', 'christmas-island');
INSERT INTO countries (code, name, slug) VALUES ('HU', 'Hungary', 'hungary');
INSERT INTO countries (code, name, slug) VALUES ('MN', 'Mongolia', 'mongolia');
INSERT INTO countries (code, name, slug) VALUES ('QA', 'Qatar', 'qatar');
INSERT INTO countries (code, name, slug) VALUES ('SS', 'South Sudan', 'south-sudan');
INSERT INTO countries (code, name, slug) VALUES ('GU', 'Guam', 'guam');
INSERT INTO countries (code, name, slug) VALUES ('PA', 'Panama', 'panama');
INSERT INTO countries (code, name, slug) VALUES ('TH', 'Thailand', 'thailand');
INSERT INTO countries (code, name, slug) VALUES ('UG', 'Uganda', 'uganda');
INSERT INTO countries (code, name, slug) VALUES ('GP', 'Guadeloupe', 'guadeloupe');
INSERT INTO countries (code, name, slug) VALUES ('NF', 'Norfolk Island', 'norfolk-island');
INSERT INTO countries (code, name, slug) VALUES ('MZ', 'Mozambique', 'mozambique');
INSERT INTO countries (code, name, slug) VALUES ('PS', 'Palestinian Territory', 'palestine');
INSERT INTO countries (code, name, slug) VALUES ('GR', 'Greece', 'greece');
INSERT INTO countries (code, name, slug) VALUES ('KR', 'Korea (South)', 'korea-south');
INSERT INTO countries (code, name, slug) VALUES ('AR', 'Argentina', 'argentina');
INSERT INTO countries (code, name, slug) VALUES ('IO', 'British Indian Ocean Territory', 'british-indian-ocean-territory');
INSERT INTO countries (code, name, slug) VALUES ('FR', 'France', 'france');
INSERT INTO countries (code, name, slug) VALUES ('KN', 'Saint Kitts and Nevis', 'saint-kitts-and-nevis');
INSERT INTO countries (code, name, slug) VALUES ('LC', 'Saint Lucia', 'saint-lucia');
INSERT INTO countries (code, name, slug) VALUES ('SR', 'Suriname', 'suriname');
INSERT INTO countries (code, name, slug) VALUES ('AX', 'ALA Aland Islands', 'ala-aland-islands');
INSERT INTO countries (code, name, slug) VALUES ('TG', 'Togo', 'togo');
INSERT INTO countries (code, name, slug) VALUES ('LS', 'Lesotho', 'lesotho');
INSERT INTO countries (code, name, slug) VALUES ('MV', 'Maldives', 'maldives');
INSERT INTO countries (code, name, slug) VALUES ('TW', 'Taiwan, Republic of China', 'taiwan');
INSERT INTO countries (code, name, slug) VALUES ('DM', 'Dominica', 'dominica');
INSERT INTO countries (code, name, slug) VALUES ('AZ', 'Azerbaijan', 'azerbaijan');
INSERT INTO countries (code, name, slug) VALUES ('NO', 'Norway', 'norway');
INSERT INTO countries (code, name, slug) VALUES ('TK', 'Tokelau', 'tokelau');
INSERT INTO countries (code, name, slug) VALUES ('UM', 'US Minor Outlying Islands', 'us-minor-outlying-islands');
INSERT INTO countries (code, name, slug) VALUES ('AD', 'Andorra', 'andorra');
INSERT INTO countries (code, name, slug) VALUES ('CU', 'Cuba', 'cuba');
INSERT INTO countries (code, name, slug) VALUES ('HN', 'Honduras', 'honduras');
INSERT INTO countries (code, name, slug) VALUES ('ML', 'Mali', 'mali');
INSERT INTO countries (code, name, slug) VALUES ('SL', 'Sierra Leone', 'sierra-leone');
INSERT INTO countries (code, name, slug) VALUES ('BG', 'Bulgaria', 'bulgaria');
INSERT INTO countries (code, name, slug) VALUES ('KM', 'Comoros', 'comoros');
INSERT INTO countries (code, name, slug) VALUES ('MS', 'Montserrat', 'montserrat');
INSERT INTO countries (code, name, slug) VALUES ('TN', 'Tunisia', 'tunisia');
INSERT INTO countries (code, name, slug) VALUES ('IR', 'Iran, Islamic Republic of', 'iran');
INSERT INTO countries (code, name, slug) VALUES ('MO', 'Macao, SAR China', 'macao-sar-china');
INSERT INTO countries (code, name, slug) VALUES ('MK', 'Macedonia, Republic of', 'macedonia');
INSERT INTO countries (code, name, slug) VALUES ('PK', 'Pakistan', 'pakistan');
INSERT INTO countries (code, name, slug) VALUES ('JP', 'Japan', 'japan');
INSERT INTO countries (code, name, slug) VALUES ('MT', 'Malta', 'malta');
INSERT INTO countries (code, name, slug) VALUES ('NA', 'Namibia', 'namibia');
INSERT INTO countries (code, name, slug) VALUES ('SB', 'Solomon Islands', 'solomon-islands');
INSERT INTO countries (code, name, slug) VALUES ('ZM', 'Zambia', 'zambia');
INSERT INTO countries (code, name, slug) VALUES ('FI', 'Finland', 'finland');
INSERT INTO countries (code, name, slug) VALUES ('SN', 'Senegal', 'senegal');
INSERT INTO countries (code, name, slug) VALUES ('KY', 'Cayman Islands', 'cayman-islands');
INSERT INTO countries (code, name, slug) VALUES ('CG', 'Congo (Brazzaville)', 'congo-brazzaville');
INSERT INTO countries (code, name, slug) VALUES ('CA', 'Canada', 'canada');
INSERT INTO countries (code, name, slug) VALUES ('CL', 'Chile', 'chile');
INSERT INTO countries (code, name, slug) VALUES ('GD', 'Grenada', 'grenada');
INSERT INTO countries (code, name, slug) VALUES ('SI', 'Slovenia', 'slovenia');
INSERT INTO countries (code, name, slug) VALUES ('BI', 'Burundi', 'burundi');
INSERT INTO countries (code, name, slug) VALUES ('DO', 'Dominican Republic', 'dominican-republic');
INSERT INTO countries (code, name, slug) VALUES ('NI', 'Nicaragua', 'nicaragua');
INSERT INTO countries (code, name, slug) VALUES ('XK', 'Republic of Kosovo', 'kosovo');
INSERT INTO countries (code, name, slug) VALUES ('BJ', 'Benin', 'benin');
INSERT INTO countries (code, name, slug) VALUES ('AM', 'Armenia', 'armenia');
INSERT INTO countries (code, name, slug) VALUES ('YT', 'Mayotte', 'mayotte');
INSERT INTO countries (code, name, slug) VALUES ('LK', 'Sri Lanka', 'sri-lanka');
INSERT INTO countries (code, name, slug) VALUES ('SZ', 'Swaziland', 'swaziland');
